version: '3.7'

services:
  db:
    image: mysql:8.0.13
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tourism
      MYSQL_USER: tour
      MYSQL_PASSWORD: 1234
    ports:
      - 13306:3306