spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/tourism?useSSL=false&&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: tour
    password: 1234
